### PR TITLE
Fixes #12 KeepAlive is not working

### LINKED ISSUE #12: KeepAlive is not working
Even if Config -> EnableKeepAlive and Config -> KeepAliveInterval are set and the connectivity is lost (i.e. internet goes down), `Session.Accept()` returns no error.
   I'm wondering if it's by design or if it is a bug. If Session.Accept doesn't return any error you can't implement fallback mechanism (e.g. redial the connection), isn't it?

### PR DESCRIPTION
**Pull request by rnapier**
This adds a timeout of `ConnectionWriteTimeout` for pings. If a keepalive fails, the connection is closed.

Modify test code to turn off keepalives on tests that want to fail for other reasons (since keepalive will tend to fail them faster than the situation under test).

### CODE REVIEW

File: session_test.go [hunk 1]
```diff
@@ -981,13 +991,7 @@ func TestSession_PingOfDeath(t *testing.T) {
 }
 
 func TestSession_ConnectionWriteTimeout(t *testing.T) {
-	// Disable keepalives so they don't detect the failed connection
```
Comment (slackpad) [inline session_test.go]: Good call in making sure these fail for the right reasons. Would you mind adding a test case that exercises your new timeout?

File: session.go [hunk 2]
```diff
@@ -286,7 +288,11 @@ func (s *Session) keepalive() {
 	for {
 		select {
 		case <-time.After(s.config.KeepAliveInterval):
-			s.Ping()
+			_, err := s.Ping()
+			if err != nil {
+				s.logger.Printf("[ERR] yamux: keepalive failed: %v", err)
+				s.Close()
```
Comment (slackpad) [inline session.go]: It would be good to know if `Close()` returns an error and log it to the console.

**Comment by slackpad** [comment]
Hi @rnapier thanks for the PR - I noted a couple small things but this is looking good!

File: session_test.go (hunk 1 above)
Comment (rnapier) [inline session_test.go]: Heh; I completely forgot the whole reason I was reworking the tests was so I could add my new test case. Sorry about that… Shortly, yes.

File: const.go [hunk 3]
```diff
@@ -48,6 +48,9 @@ var (
 	// ErrConnectionWriteTimeout indicates that we hit the "safety valve"
 	// timeout writing to the underlying stream connection.
 	ErrConnectionWriteTimeout = fmt.Errorf("connection write timeout")
+
+	// ErrKeepAliveTimeout is sent if a missed keepalive caused the stream close
+	ErrKeepAliveTimeout = fmt.Errorf("keepalive timeout")
```
Comment (rnapier) [inline const.go]: I added a new, explicit error rather than reusing ErrTimeout. I realized that the caller needs to differentiate.

File: session.go [hunk 4]
```diff
@@ -286,7 +291,12 @@ func (s *Session) keepalive() {
 	for {
 		select {
 		case <-time.After(s.config.KeepAliveInterval):
-			s.Ping()
+			_, err := s.Ping()
+			if err != nil {
+				s.logger.Printf("[ERR] yamux: keepalive failed: %v", err)
+				s.exitErr(ErrKeepAliveTimeout)
+				return
+			}
```
Comment (rnapier) [inline session.go]: You mentioned checking the `Close()` error, but I'm not sure what I would do with it. I switched to using your usual pattern of `exitErr()`.

File: session_test.go [hunk 5]
```diff
@@ -5,12 +5,31 @@ import (
...
+func (l *logCapture) match(expect []string) bool {
+	return reflect.DeepEqual(l.logs(), expect)
+}
+
+func captureLogs(s *Session) *logCapture {
+	buf := new(logCapture)
+	s.logger = log.New(buf, "", 0)
+	return buf
+}
+
```
Comment (rnapier) [inline session_test.go]: I consider logging an important part of the API. I also don't like "expected" errors in the test output. I can add this feature to the other things that currently spit logs if you like.

File: session.go (hunk 4 above)
Comment (slackpad) [inline session.go]: I was thinking of just logging, but `exitErr` is the way to go.

File: session_test.go (hunk 5 above)
Comment (slackpad) [inline session_test.go]: Definitely agree, and thanks! It would be out of scope on this change, but I'd welcome a follow on PR for it.

File: session_test.go [hunk 6]
```diff
@@ -663,6 +734,57 @@ func TestKeepAlive(t *testing.T) {
...
+	select {
+	case err := <-errCh:
+		if err != ErrKeepAliveTimeout {
+			t.Fatalf("unexpected error: %v", err)
+		}
+	case <-time.After(1 * time.Second):
+		t.Fatalf("timeout waiting for timeout")
+	}
+
+	if !client.IsClosed() {
```
Comment (slackpad) [inline session_test.go]: Running locally it looks like the test is flaky some times right here.

```
workpad:yamux james$ untilfail go test ./...
ok      _/Users/james/projects/rnapier/yamux    12.165s
ok      _/Users/james/projects/rnapier/yamux    11.947s
2015/09/10 10:47:53 [ERR] yamux: keepalive failed: session shutdown
2015/09/10 10:47:53 [ERR] yamux: keepalive failed: session shutdown
--- FAIL: TestKeepAlive_Timeout-4 (0.35s)
        session_test.go:772: client should have closed
2015/09/10 10:48:03 [WARN] yamux: failed to send ping reply: connection write timeout
FAIL
FAIL    _/Users/james/projects/rnapier/yamux    11.800s
```

You could probably remove the client-side checks since all the action is on the server side for this one, or add a small delay for the client to finish the close. I'm puzzled who is emitting `[WARN] yamux: failed to send ping reply: connection write timeout` though, that must be the server but it should be able to do the write.

**Comment by slackpad** [comment]
Changes all LGTM - just one question on there about a little flakyness in one of the unit tests.

**Comment by rnapier** [comment]
Sounds good. I'll fix it up on Monday when I'm back from the mountains.

**Comment by rnapier** [comment]
I think this is now ready to go.

**Comment by slackpad** [comment]
Thanks for this!
