### PR TITLE
Fix unsafe header re-use on close and timeout

### LINKED ISSUE #40: Send timeout might corrupt outgoing messages
Hi everyone,

I just reviewed the library a little bit since I'm also interested in stream multiplexing (actually want something for websockets instead of plain TCP, but I guess yamux would work there too).
Overall it looks really well written and I like the fact that you have a spec :-)

One thing that I stumbled upon during review was there might be situations where the send timeout for the session might corrupt outgoing data: If we look at the `waitForSendErr` function it will start the timout and try to send the data in parallel be handing it over to the send channel. 

The select/timeout logic looks like it introduces a data race to me: If the timeout is expiring here the send will still be in progress. That means the data (header and body) will still be in use in the send routine. However the `waitForSendErr` call returns with an the calling stream could think the data is no longer required and reuse it. It might probably not do it for `sendHdr` as it sees that writes fail and no further writes and `sendHdr` mutations follow, but the payload data slice might be reused by the application and mutated - while the send is still in progress. As an end result you could send data to the wire that was not desired.

Fixing this is probably not that easy. I guess that there probably could be some cancellation or sendInProgress flags in the enqueued `sendReady` struct. If the message was not yet fetched by the writing proc it can be marked as cancelled and will there no longer be processed. However as soon as the writer goroutine catches it the safest thing is to let it write to completion as there is no kind of CancellationToken that can be passed to to the `Write` or `Copy` methods.

### PR DESCRIPTION
**Pull request by mafredri**
This commit takes a minimal approach to fixing unsafe header re-use during close and timeout by reallocating the header in those cases.

Fixes #40
Related #102

### CODE REVIEW

File: stream.go [hunk 1]
```diff
@@ -200,6 +201,10 @@ START:
 	// Send the header
 	s.sendHdr.encode(typeData, flags, s.id, max)
 	if err = s.session.waitForSendErr(s.sendHdr, body, s.sendErr); err != nil {
+		if errors.Is(err, ErrSessionShutdown) || errors.Is(err, ErrConnectionWriteTimeout) {
```
Comment (evanphx) [inline stream.go:204]: This makes yamux depend on Go 1.13 or later. That's not necessarily a problem, but it should be noted as such.

Comment (jefferai) [reply stream.go:204]: I don't even think it needs to be noted, TBH. Go 1.13 is _well_ outside the security update window and should not be used any longer (or for the past year +)
